### PR TITLE
Fix misprint

### PR DESCRIPTION
**Pull request by mvasin**

### CODE REVIEW

**Comment by janko** [comment]
Thanks, but `uid` was actually used here on purpose (it means "**u**nique **id**entifier"), because it's the same terminology that's used in the implementation of tus-ruby-server, and so that it distinguishes from Shrine's `id`.

**Comment by janko** [comment]
Oh, I see now what you meant, the examples were using both `tus_uid` and `tus_id`, fixed now.

**Comment by mvasin** [comment]
Yeah, it was hard to guess, `tus_uid` or `tus_id`, but most likely not both of them.

**Comment by mvasin** [comment]
@janko-m Seems like it's wrong now in S3 section at the bottom of the readme page, should be `tus_uid`.

**Comment by janko** [comment]
@mvasin Fixed in the latest changes, this code was now moved to the [shrine-tus](https://github.com/janko-m/shrine-tus) gem, where tests will ensure there are no typos (and the user doesn't have to know about the logistics anymore).

**Pull request closed without merging**
